# Generated by Django 5.0.7 on 2024-07-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordmapping',
            name='userID',
        ),
        migrations.AddField(
            model_name='forgotpasswordmapping',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
