# Generated by Django 5.0.7 on 2024-07-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='userID',
            new_name='ID',
        ),
    ]
