# Generated by Django 5.0.7 on 2024-07-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_userid_usermodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='ID',
            new_name='userID',
        ),
    ]
